### ISSUE TITLE
shift to quarto

### ISSUE THREAD

**Issue by ernestguevarra** [ecohealthalliance/acdc-db-handbook#11]
```[tasklist]
### Tasks
- [ ] https://github.com/ecohealthalliance/rig-handbook/issues/12
- [ ] https://github.com/ecohealthalliance/rig-handbook/issues/13
- [ ] https://github.com/ecohealthalliance/rig-handbook/issues/14
- [ ] https://github.com/ecohealthalliance/rig-handbook/issues/15
- [ ] https://github.com/ecohealthalliance/rig-handbook/issues/16
```
