### ISSUE TITLE
update chapters

### ISSUE THREAD

**Issue by ernestguevarra** [ecohealthalliance/acdc-db-handbook#33]
```[tasklist]
### Tasks
- [ ] edit database chapter
- [ ] edit sources chapter
- [ ] edit updates chapter
```
